version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network
    environment:
      - VITE_SPREADSHEET_ID=${SPREADSHEET_ID:-default_spreadsheet_id}
      - VITE_API_BASE_URL=http://backend_api:5000
    depends_on:
      - backend_api

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongodb-data/seed:/seed
      - ./mongodb-data/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  backend_api:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    command: |
      sh -c "
      wget -q https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /wait-for-it.sh &&
      chmod +x /wait-for-it.sh &&
      /wait-for-it.sh mongo:27017 -t 30 &&
      npm run dev"
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DB_URI=mongodb://mongo:27017
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET:-your_default_jwt_secret}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - FACE_RECOGNITION_API_URL=http://face:8000
      - SPREADSHEET_ID=${SPREADSHEET_ID:-default_spreadsheet_id}
    depends_on:
      - face
      - mongo

  face:
    build:
      context: ./face
    container_name: face
    ports:
      - "8000:8000"
    volumes:
      - ./face:/face
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network: