version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network
    environment:
      - VITE_SPREADSHEET_ID=105Ar8i2bg1aPccDAtIut8xKvugGNYpHUcM6u1T0CZ64
      - VITE_API_BASE_URL=http://backend_api:5000

    depends_on:
      -  backend_api

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./mongodb-data/data:/seed
      - ./mongodb-data/init:/docker-entrypoint-initdb.d

    networks:
      - app-network

  backend_api:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    command: |
      sh -c "
      wget -q https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /wait-for-it.sh &&
      chmod +x /wait-for-it.sh &&
      /wait-for-it.sh face:8000 -t 30 -- npm run dev"
    networks:
      - app-network
    environment:
      - DB_URI=mongodb://mongo:27018
      - PORT=5000
      - JWT_SECRET=<your_jwt_secret>
      - CLOUDINARY_CLOUD_NAME=<your_cloud_name>
      - CLOUDINARY_API_KEY=<your_api_key>
      - CLOUDINARY_API_SECRET=<your_api_secret>
      - FACE_RECOGNITION_API_URL=http://0.0.0.0:8000
      - SPREADSHEET_ID=<your_spreadsheet_id>
      
    depends_on:
      - face
      - mongo

  face:
    build:
      context: ./face
    container_name: face
    ports:
      - "8000:8000"
    volumes:
      - ./face:/face
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
